version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 15432:5432
